baseURL = 'https://www.tavisto.net/'
title = 'Tavisto.net'
theme = 'hugo-coder'

languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true
enableRobotsTXT = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Tavis Aitken"
  license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA-4.0</a>'
  description = "Tavisto's space to write about things."
  info = [ "Leader", "Technology Wrangler","Productivity Enthusiast" ]
  keywords = "blog,developer,sre,devops,productivity"
  gravatar = "tavisto@tavisto.net"
  since = 2009

# Theme Settings
  colorScheme = "auto" # Let the browser decide
  hidecolorschemetoggle = false # Let the user decide

[params.googleTagManager]
  id = "GTM-WS5QDS"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tavisto/"
[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 3
  url = "https://bsky.app/profile/bsky.tavisto.net"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/tavisaitken/"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 6
  url = "https://www.tavisto.net/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[menu.main]]
  name = "Posts"
  weight = 1
  url = "/posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"

